trigger:
  batch: true
  branches:
    include:
      - main

pr:
  - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "hmcts"

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy
  - name: environment_components
    type: object
    default:
      - deployment: "sandbox_core"
        environment: "sbox"
        component: "core"
        service_connection: "DCD-CFTAPPS-SBOX"
        dependsOn: "Precheck"
      - deployment: "sandbox_database"
        environment: "sbox"
        component: "database"
        service_connection: "DCD-CFTAPPS-SBOX"
        dependsOn: "sandbox_core"
      - deployment: "sandbox_container_app"
        environment: "sbox"
        component: "container-app"
        service_connection: "DCD-CFTAPPS-SBOX"
        dependsOn:
          - "sandbox_core"
          - "sandbox_database"
      - deployment: "sandbox_datafactory"
        environment: "sbox"
        component: "datafactory"
        service_connection: "DCD-CFTAPPS-SBOX"
        dependsOn:
          - "sandbox_core"
          - "sandbox_database"
      - deployment: "dev_core"
        environment: "dev"
        component: "core"
        service_connection: "DCD-CFTAPPS-DEV"
        dependsOn: "sandbox_core"
      - deployment: "dev_database"
        environment: "dev"
        component: "database"
        service_connection: "DCD-CFTAPPS-DEV"
        dependsOn: 
          - "dev_core"
          - "sandbox_database"
      - deployment: "dev_container_app"
        environment: "dev"
        component: "container-app"
        service_connection: "DCD-CFTAPPS-DEV"
        dependsOn:
          - "dev_core"
          - "dev_database"
          - "sandbox_container_app"
      - deployment: "dev_datafactory"
        environment: "dev"
        component: "datafactory"
        service_connection: "DCD-CFTAPPS-DEV"
        dependsOn:
          - "dev_core"
          - "dev_database"
          - "sandbox_datafactory"
      - deployment: "stg_core"
        environment: "stg"
        component: "core"
        service_connection: "DCD-CFTAPPS-STG"
        dependsOn: "dev_core"
      - deployment: "stg_database"
        environment: "stg"
        component: "database"
        service_connection: "DCD-CFTAPPS-STG"
        dependsOn: 
          - "stg_core"
          - "dev_database"
      - deployment: "stg_container_app"
        environment: "stg"
        component: "container-app"
        service_connection: "DCD-CFTAPPS-STG"
        dependsOn:
          - "stg_core"
          - "stg_database"
          - "dev_container_app"
      - deployment: "stg_datafactory"
        environment: "stg"
        component: "datafactory"
        service_connection: "DCD-CFTAPPS-STG"
        dependsOn:
          - "stg_core"
          - "stg_database"
          - "dev_datafactory"
      - deployment: "prod_core"
        environment: "prod"
        component: "core"
        service_connection: "DCD-CFTAPPS-PROD"
        dependsOn: "stg_core"
      - deployment: "prod_database"
        environment: "prod"
        component: "database"
        service_connection: "DCD-CFTAPPS-PROD"
        dependsOn: 
          - "prod_core"
          - "stg_database"
      - deployment: "prod_container_app"
        environment: "prod"
        component: "container-app"
        service_connection: "DCD-CFTAPPS-PROD"
        dependsOn:
          - "prod_core"
          - "prod_database"
          - "stg_container_app"
      - deployment: "prod_datafactory"
        environment: "prod"
        component: "datafactory"
        service_connection: "DCD-CFTAPPS-PROD"
        dependsOn:
          - "prod_core"
          - "prod_database"
          - "stg_datafactory"

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentImage
    value: ubuntu-latest
  - name: product
    value: csds
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job:
        pool:
          vmImage: ${{ variables.agentImage }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: "infra-vault-nonprod"
              keyvaultSecret: "azure-devops-sp-token"
              serviceConnection: "azurerm-sandbox"
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - job: TerraformPlanApply
            pool: hmcts-cftptl-agent-pool
            timeoutInMinutes: ${{ variables.timeoutInMinutes }}
            steps:
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.overrideAction }}
                  environment: ${{ deployment.environment}}
                  component: ${{ deployment.component }}
                  serviceConnection: ${{ deployment.service_connection }}
                  product: ${{ variables.product }}
                  terraformInitSubscription: ${{ variables.terraformInitSubscription }}
